In [1]:
import numpy as np
import pandas as pd

In [2]:
# Exercise 1: Create a numpy array and reshape it to a 2x5 matrix
arr1 = np.arange(1, 11).reshape(2, 5)
print("Exercise 1:\n", arr1)

Exercise 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
# Exercise 2: Extract elements between the 5th and 15th index
arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]
print("\nExercise 2:\n", extracted_elements)



Exercise 2:
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [4]:
# Exercise 3: Create a Pandas series and add a new item
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4
print("\nExercise 3:\n", fruit_series)


Exercise 3:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [6]:
# Exercise 4: Create a dataframe with 10 rows of data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 35, 40, 28, 32, 29, 41, 26],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
print("\nExercise 4:\n", df)


Exercise 4:
       name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    David   35      M
4      Eve   40      F
5    Frank   28      M
6    Grace   32      F
7   Hannah   29      F
8      Ian   41      M
9     Jack   26      M


In [7]:
# Exercise 5: Add a new column 'occupation'
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("\nExercise 5:\n", df)



Exercise 5:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4      Eve   40      F     Manager
5    Frank   28      M     Analyst
6    Grace   32      F  Programmer
7   Hannah   29      F     Manager
8      Ian   41      M     Analyst
9     Jack   26      M  Programmer


In [8]:
# Exercise 6: Select rows where age is greater than or equal to 30
filtered_df = df[df['age'] >= 30]
print("\nExercise 6:\n", filtered_df)


Exercise 6:
     name  age gender  occupation
1    Bob   30      M     Manager
3  David   35      M  Programmer
4    Eve   40      F     Manager
6  Grace   32      F  Programmer
8    Ian   41      M     Analyst


In [9]:

# Exercise 7: Convert dataframe to CSV and read it back
df.to_csv("data.csv", index=False)
df_read = pd.read_csv("data.csv")
print("\nExercise 7:\n", df_read)


Exercise 7:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4      Eve   40      F     Manager
5    Frank   28      M     Analyst
6    Grace   32      F  Programmer
7   Hannah   29      F     Manager
8      Ian   41      M     Analyst
9     Jack   26      M  Programmer
